[build]
  command = "npm run build"
  publish = ".next"
  functions = ".next/server"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]
  included_files = [".env.local"]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
