[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
