[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"
  node = "18"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_OPENAI_API_KEY = "your_api_key_here"

[build.environment.pnpm]
  public_hoist_pattern = ["*", "!react", "!react-dom"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
