[build]
  base = "/"
  command = "pnpm install && pnpm approve-builds && pnpm run build"
  publish = "/.next"
  node = "18"

[context.production.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
