[build]
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[build.environment.pnpm]
  public_hoist_pattern = ["*", "!react", "!react-dom"]
  store_directory = ".pnpm-store"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수는 Netlify 대시보드에서 설정해주세요
# OPENAI_API_KEY
