[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 환경 변수는 Netlify 대시보드에서 설정해주세요
# OPENAI_API_KEY
# NEXT_PUBLIC_SUPABASE_URL (필요한 경우)
# NEXT_PUBLIC_SUPABASE_ANON_KEY (필요한 경우)
