[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]
  included_files = [".env.local"]
  node_bundler = "esbuild"
  timeout = 10  # 10초 타임아웃

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = ".next"
  framework = "next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
